### ISSUE TITLE
conan package

### ISSUE THREAD

**Issue by dvirtz** [dfleury2/beauty#4]
Is it possible to consume the package through conan? I can't find it in conan center

**Comment by dfleury2** [comment]
Hi,
I need to fix the conanfile.py but yes it should be possible to use it with conan (I doing it at my job).
I have not try to add it to conan-center (nor plan to make it). May be later. I am not sure I know how to to that anyway ;)

**Comment by dvirtz** [comment]
so you suggest to clone the repo and run `conan create` from it? that's possible but I think is against the idea of using a package manager.
I can try to add it to conan-center as I already added some packages there. 
Do you plan to cut a release soon so it can be versioned properly?

**Comment by dfleury2** [comment]
Yes, since I just fix the recipe, it should work by cloning and launch a conan create. (https://github.com/dfleury2/beauty/commit/a5b9c266787889b93627d7987511312e521e02b2)
Yes against a centralized package manager. I am used to create conan recipe for third parties which do not belong to conan-center.

I will see how I can add it to conan-center myself so I can learn how to to it ;) In case of trouble, I can still ask you advice.

Soon I will tag a first rc release. I still need to fix an issue on the asynchronous client.

**Comment by dfleury2** [comment]
tag 1.0.0-rc1 created.
conan-center-index package is done (need to test it) but I need to be accepted to push first.

**Comment by dfleury2** [comment]
Hi,
conan package review is in progress. Waiting for 3 reviewer approvals.

https://github.com/conan-io/conan-center-index/pull/10956

**Comment by dfleury2** [comment]
Done

https://conan.io/center/beauty
